### ISSUE TITLE
Russia auto-peace with Entente 

### ISSUE THREAD

**Issue by Troller07** [KR4/Kaiserreich-Darkest-Hour#27]
After beating German Empire as National Populist Russia in Europe (Savenkov), they joined Entente and drag them into  war against me. After i annexed Delhi and liberated India (Indian Federation which had a flag of Princely Federation, not a Russian Indian(shield_IND_RUS)), auto-event  happens for India that causes auto-peace with Entente for me.

**Comment by IllyaTokar** [comment]
Fixed by making the event check whether IND is a puppet.
